# Site
name: "WebGov"
title: "WebGov"
description: "Blog on web elements and governance"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /webgov-be.github.io
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Eveline:
    name: Eveline 
    display_name: Eveline
    gravatar: fdb570aed748bfa98f2191cd28f9718e
    email: eveline.vlassenroot@ugent.be
    web: https://biblio.ugent.be/person/000110474714
    twitter: https://twitter.com/evelinevlas
    description: "Researcher at imec-mict-UGent."
  Mathias:
    name: Mathias 
    display_name: Mathias
    email: mathias.vancompernolle@ugent.be
    web: https://biblio.ugent.be/person/002004496411
    twitter: https://twitter.com/mvcomper
    description: "Researcher at imec-mict-UGent."
  gastauteur:
    name: Gastauteur
    display_name: Gastauteur
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
